apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: telegram-bot-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
        - name: telegram-bot
          image: telegram-bot:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: telegram-bot-config
            - secretRef:
                name: telegram-bot-secret

