apiVersion: v1
kind: Service
metadata:
  name: telegram-bot
  namespace: telegram-bot-ns
spec:
  selector:
    app: telegram-bot
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
  type: NodePort
