apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: notification-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: notification-config
            - configMapRef:
                name: postgres-notification-config
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: postgres-notification-secret
            - secretRef:
                name: rabbitmq-secret
