apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: notification-ns
spec:
  selector:
    app: notification-service
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30084
  type: NodePort
