apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-ns
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.postgres-ns.svc.cluster.local:5432/telegram_bot
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: none
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_PROFILES_ACTIVE: docker