apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user-service-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user-service-config
          volumeMounts:
            - name: user-data
              mountPath: /data
      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: user-service-pvc
