apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: user-service-ns
spec:
  selector:
    app: user-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
