apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
  namespace: postgres-notification-ns
spec:
  selector:
    app: postgres-notification
  ports:
    - port: 5432
  type: ClusterIP
