--liquibase formatted sql

--changeset alex:1
CREATE TABLE notifications
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL,
    type        VARCHAR(5)               NOT NULL,
    message     TEXT                     NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO notifications (user_id, type, message, received_at)
VALUES
-- User 1
(1, 'START', 'Workday started', '2024-01-01T09:00:00Z'),
(1, 'STOP', 'Workday ended', '2024-01-01T18:00:00Z'),
-- User 2
(2, 'START', 'Workday started', '2024-02-15T08:30:00Z'),
(2, 'STOP', 'Workday ended', '2024-02-15T17:45:00Z'),
-- User 3
(3, 'START', 'Workday started', '2024-03-10T10:15:00Z'),
(3, 'STOP', 'Workday ended', '2024-03-10T19:20:00Z');

--changeset alex:2
ALTER TABLE notifications
    ALTER COLUMN type TYPE VARCHAR(30);
